export const QUESTION_ADD_START = 'QUESTION_ADD_START';
export const QUESTION_ADD_END = 'QUESTION_ADD_END';
export const QUESTION_ADD_SUCCESS = 'QUESTION_ADD_SUCCESS';
export const QUESTION_ADD_FAILURE = 'QUESTION_ADD_FAILURE';

export const QUESTION_UPDATE_START = 'QUESTION_UPDATE_START';
export const QUESTION_UPDATE_END = 'QUESTION_UPDATE_END';
export const QUESTION_UPDATE_SUCCESS = 'QUESTION_UPDATE_SUCCESS';
export const QUESTION_UPDATE_FAILURE = 'QUESTION_UPDATE_FAILURE';

export const QUESTION_DISPLAY_START = 'QUESTION_DISPLAY_START';
export const QUESTION_DISPLAY_END = 'QUESTION_DISPLAY_END';
export const QUESTION_DISPLAY_SUCCESS = 'QUESTION_DISPLAY_SUCCESS';
export const QUESTION_DISPLAY_FAILURE = 'QUESTION_DISPLAY_FAILURE';

export const QUESTION_DELETE_START = 'QUESTION_DELETE_START';
export const QUESTION_DELETE_END = 'QUESTION_DELETE_END';
export const QUESTION_DELETE_SUCCESS = 'QUESTION_DELETE_SUCCESS';
export const QUESTION_DELETE_FAILURE = 'QUESTION_DELETE_FAILURE';

export const QUESTION_CORRECTION_START = 'QUESTION_CORRECTION_START';
export const QUESTION_CORRECTION_END = 'QUESTION_CORRECTION_END';
export const QUESTION_CORRECTION_SUCCESS = 'QUESTION_CORRECTION_SUCCESS';
export const QUESTION_CORRECTION_FAILURE = 'QUESTION_CORRECTION_FAILURE';

export const QUIZ_MARKS_START = 'QUIZ_MARKS_START';
export const QUIZ_MARKS_END = 'QUIZ_MARKS_END';
export const QUIZ_MARKS_SUCCESS = 'QUIZ_MARKS_SUCCESS';
export const QUIZ_MARKS_FAILURE = 'QUIZ_MARKS_FAILURE';

export const ALL_MARKS_START = 'ALL_MARKS_START';
export const ALL_MARKS_END = 'ALL_MARKS_END';
export const ALL_MARKS_SUCCESS = 'ALL_MARKS_SUCCESS';
export const ALL_MARKS_FAILURE = 'ALL_MARKS_FAILURE';
